### ISSUE TITLE
The minimap (possibly map as well) can be missing (either transparent or white) for some users

### ISSUE THREAD

**Issue by CringeAura** [Wynntils/Wynntils-Legacy#118]
![image](https://user-images.githubusercontent.com/14227259/61008754-506dc780-a325-11e9-941c-1f48569e39ab.png)

**Comment by HighCrit** [comment]
@CringeAura Which ticket # was this?

**Comment by HeyZeer0** [comment]
Not sure but it seems that this issue is correlated to 32 bits operational systems

**Comment by HighCrit** [comment]
Could it be RAM related as well?

**Comment by CringeAura** [comment]
@HighCrit It's from ticket 0257
