### ISSUE TITLE
Apostrophes do not render correctly and a territory box can sometimes be overlapped by two guilds

### ISSUE THREAD

**Issue by CringeAura** [Wynntils/Wynntils-Legacy#122]
![image](https://user-images.githubusercontent.com/14227259/61152962-b16cdb00-a49e-11e9-866c-7321704a8685.png)

**Comment by CringeAura** [comment]
The issue with apostrophes rendering incorrectly were somehow magically fixed after https://github.com/Wynntils/Wynntils/commit/fe95c931ff72b48f998cdc04e6a5b2f1eff1bf0d or https://github.com/Wynntils/Wynntils/commit/8be5e4e2010234b8f5961ccb95541392c448abb4, but they have been reported to render incorrectly again.

**Comment by Bedo9041** [comment]
Hopefully fixed by https://github.com/Wynntils/Wynntils/commit/0f319dbc2a2cfe73f6862238bb6161ba99c49af8 re-open if not
