### ISSUE TITLE
Nemract does not play proper music

### ISSUE THREAD

**Issue by rbazzell** [Wynntils/Wynntils-Legacy#133]
The music player plays Unfamiliar Lands (Nemract Swamp) instead of Muddy Outlook (Nemract) while in Nemract.

**Comment by rbazzell** [comment]
Black road doesn't play proper music either

**Comment by Chew** [comment]
This might be an issue with Wynncraft itself. Consider using the Bug Report forum to report it there.
https://forums.wynncraft.com/forums/bug-reports.108/
