### ISSUE TITLE
[Bug] Clicking back on Discoveries goes to Quests

### ISSUE THREAD

**Issue by Chew** [Wynntils/Wynntils-Legacy#139]
Probably due to the mechanic of clicking Discoveries on the Quest tab. It can probably be removed from the Quest tab in all honesty.

**Comment by CringeAura** [comment]
This is an intended feature and not a bug. However, this behavior could be looked into by the developers.

**Comment by Chew** [comment]
I should elaborate, sorry. Clicking discoveries from the Main Menu (NOT going to quest tab first) then clicking back goes to quest. See the video I've attached for more info

[Video](https://cdn.discordapp.com/attachments/457230849277165610/612466305462698014/fehwofuhwefew.mov)

**Comment by CringeAura** [comment]
After checking with the developers, they still have said that this is an intended behavior based on the video you have attached. There is a possibility that this behavior could be changed, however.

**Comment by Chew** [comment]
Alright, thanks for following up!
