### ISSUE TITLE
Getting disconnected doesn't makes you load the resourcepack again

### ISSUE THREAD

**Issue by HeyZeer0** [Wynntils/Wynntils-Legacy#140]
Getting disconnected/kicked from the server makes the resource pack not load anymore

Probably causes: WynncraftServerEvent.Leave is not being triggered when that happens

**Comment by MitalAshok** [comment]
a4462c45d16089935b6afcdebc0fa72db72ace9a should fix this, but doesn't fix leave event not being fired if it isn't.

**Comment by coehlrich** [comment]
69d8035cf37310eab1e517f5a8dfa78f30adb527 and fb8551abe55f925180d38f296aa95a6eae8502b7 fixes the leave event not firing
