### ISSUE TITLE
People with [Art] rank do not have the Wynncraft CT tag

### ISSUE THREAD

**Issue by CringeAura** [Wynntils/Wynntils-Legacy#144]

**Comment by CringeAura** [comment]
The Wynncraft Artist rank still does not show up despite https://github.com/Wynntils/Wynntils/pull/151 (the artist in question is LoveLusting) 

![2019-11-17_14 11 35](https://user-images.githubusercontent.com/14227259/69014971-49df0480-0944-11ea-8112-06ab8a2ff48a.png)

**Comment by BurstingF** [comment]
Everyone in the lobby is part of the "all" team. This means that in the lobby nobody will have a rank based on their position on the wynncraft server since the detection on whether we have to a add a nametag is based on their team.

**Comment by CringeAura** [comment]
Ah, alright. In that case, I'll try to find LoveLusting in an actual world and report back my findings.

**Comment by HeyZeer0** [comment]
Will be fixed when 1.19 be released
