### ISSUE TITLE
Game crashes at market place

### ISSUE THREAD

**Issue by bugbustr** [Wynntils/Wynntils-Legacy#173]
When entering market place and clicking some of the things for sale, I get this crash report.
[crash-2020-01-09_23.30.42-client.txt](https://github.com/Wynntils/Wynntils/files/4042900/crash-2020-01-09_23.30.42-client.txt)

**Comment by bugbustr** [comment]
I tested this a bit more, and found that the crash occurs each time I'm about to click a certain spear in the Lv.1-19 part of the market place.

**Comment by magicus** [comment]
I can confirm this bug. I did some testing with @bugbustr and we found out it's a Depressing Spear that triggers this.

**Comment by magicus** [comment]
It is the latest version available on Jenkins, 1.0.3_632.

**Comment by magicus** [comment]
The problematic piece of code is this:
```
                int[] money = calculateMoneyAmount(market.getInteger("price"));
                String price = "";
                if (money[3] != 0) price += money[3] + "stx ";
                if (money[2] != 0) price += money[2] + EmeraldSymbols.LE + " ";
                if (money[1] != 0) price += money[1] + EmeraldSymbols.BLOCKS + " ";
                if (money[0] != 0) price += money[0] + EmeraldSymbols.EMERALDS + " ";

                price = price.substring(0, price.length() - 1);
```

I'll check if I can see if there's anything weird with the pricing of the spear in question. In any case, some more defensive programming could be useful here :)

**Comment by magicus** [comment]
Nothing weird that I could tell from the vanilla client. But the NBT might be borked anyway.

![2020-01-10_00 29 15](https://user-images.githubusercontent.com/6209108/72113322-65f99380-3340-11ea-88a8-12a9d029e55e.png)
