### ISSUE TITLE
Friends/Party members not showing on map

### ISSUE THREAD

**Issue by Aruloci** [Wynntils/Wynntils-Legacy#174]
Sometimes my friends or the people in my party are not showing on the minimap. I have no idea how to reproduce this or know of a workaround. Sometimes it just starts working again.

**Comment by MrToWy** [comment]
same experience here. it worked only on one day.

**Comment by DevChromium** [comment]
Hello!

We currently have this feature disabled because we have updated our back-end services to make the mod better. This feature will be supported again in the future, an exact date cannot be specified yet but it will be available again.

Kind regards,
_Chromium_
