### ISSUE TITLE
Wynntils confirm GUIs removes search/jump rendering

### ISSUE THREAD

**Issue by ryanzhoudev** [Wynntils/Wynntils-Legacy#378]
### Version

Build 1375 (development 7443c8d735e06d76ef62693ac472f20d42e238bc)

### Brief Description

All three Wynntils bank confirms (the new page one, the stash one, and the dump one), all kill the rendering for the search box and the page jump buttons. Page jump buttons are still functional, just are invisible. Search box does not exist and is therefore no longer functional.
Fixed on bank page change.

### Steps to Reproduce

- Open bank
- trigger a confirm (attempt to purchase new page, attempt to dump inventory, etc)
- click "no"
- observe

### Expected Behaviour

Jump buttons + search box doesn't disappear

### Actual Behaviour

Jump buttons + search box disappears until page is changed
See [image](https://cdn.discordapp.com/attachments/743928502314598511/909419782011494420/unknown.png)

### Installed Mods

Wynntils, Phosphor

**Comment by Incompleteusern** [comment]
```java
                    McIf.mc().displayGuiScreen(new GuiYesNo((result, parentButtonID) -> {
                        McIf.mc().displayGuiScreen(gui);
                        if (result) {
                            McIf.mc().getConnection().sendPacket(packet);
                            bankPageConfirmed = true;
                        }
                    }, "Are you sure you want to dump your inventory?", "This confirm may be disabled in the Wynntils config.", 0));
```

```java
    @SubscribeEvent
    public void onBankClose(GuiOverlapEvent.ChestOverlap.GuiClosed e) {
        // reset everything
        page = 0;
        inBank = false;
        itemsLoaded = false;
        nameField = null;
        searchedItems.clear();
        Keyboard.enableRepeatEvents(false);
    }
```

```java

    @SubscribeEvent
    public void onBankInit(GuiOverlapEvent.ChestOverlap.InitGui e) {
        Matcher m = PAGE_PATTERN.matcher(TextFormatting.getTextWithoutFormattingCodes(e.getGui().getLowerInv().getName()));
        if (!m.matches()) return;

        inBank = true;
        page = Integer.parseInt(m.group(1));
        updateMaxPages();

        if (UtilitiesConfig.Bank.INSTANCE.pageNames.containsKey(page))
            updateName(e.getGui().getLowerInv());

        if (destinationPage == page) destinationPage = 0; // if we've already arrived, reset destination

        if (searchField == null && UtilitiesConfig.Bank.INSTANCE.showBankSearchBar) {
            //create search bar
        }
        ...
    }
```

The list of events that occur is as followed:
1. Bank is opened, BankOverlay initalizes overlay and renames open page
2. Quick Stash/Dump/New Page confirm is activated, displays confirmation page and BankOverlay closes overlay as gui is closed
3. No is pressed in confirm page, bank ChestReplacer is reactivated, but doesn't match as the name has been changed so doesn't reinitalize overlay

Fixing this seems hard

**Comment by Incompleteusern** [comment]
Nicest solution imo is making BankOverlay a replacer like ChestReplacer and keep all the relavant overlay stuff to the gui, nice thing is that no need to uninitalize overlay manually, as gc does that for you.
