### ISSUE TITLE
Wynntils confirm GUIs break bank when closed with esc key

### ISSUE THREAD

**Issue by ryanzhoudev** [Wynntils/Wynntils-Legacy#379]
### Version

Build 1375 (development 7443c8d735e06d76ef62693ac472f20d42e238bc)

### Brief Description

When closing the bank confirm, stash confirm, or dump confirm with the escape key, you cannot open the bank until you /class

### Steps to Reproduce

- trigger a confirm page
- press escape instead of yes/no button
- cannot open bank anymore

### Expected Behaviour

Pressing escape key closes all guis, but does not break bank opening functionality

### Actual Behaviour

Pressing escape key disables bank temporarily

### Installed Mods

Wynntils, Phosphor

**Comment by Incompleteusern** [comment]
The cause of this is that displayGUI replaces the previously open bank gui as the field `currentscreen` and as such when the  confirmation gui is closed, the confirmation gui disappears on the client side, and the bank gui doesn't reappear. However, the server knows the gui is still open, so you can't reopen the bank as the gui is already open.

As GuiYesNo is minecraft's inbuilt, a fix would likely involve either using `setWorldAndResolution` which activates the gui without closing and then saving that, or overriding GuiYesNo and have it open the previous screen if confirmation screen iss closed.

**Comment by Incompleteusern** [comment]
```java
                    McIf.mc().displayGuiScreen(new GuiYesNo((result, parentButtonID) -> {
                        McIf.mc().displayGuiScreen(gui);
                        if (result) {
                            McIf.mc().getConnection().sendPacket(packet);
                            bankPageConfirmed = true;
                        }
                    }, "Are you sure you want to dump your inventory?", "This confirm may be disabled in the Wynntils config.", 0));
```

displayGuiScreen replaces the field `currentscreen` in minecraft, and 

Escaping a GuiYesNo runs
```java
    protected void keyTyped(char typedChar, int keyCode) throws IOException
    {
        if (keyCode == 1)
        {
            this.mc.displayGuiScreen((GuiScreen)null);

            if (this.mc.currentScreen == null)
            {
                this.mc.setIngameFocus();
            }
        }
    }
```
which closes active the `currentscreen`, meaning on the clientside no guis are open.
However, the server still believes that the bank gui is open, as such preventing new guis being opened and weird things happening.

One fix would be overriding GuiYesNo to run the callback when closed by the following due to keyTyped, something like
```java
    @Override
    protected void keyTyped(char typedChar, int keyCode) throws IOException
    {
        if (keyCode == 1)
        {
            this.mc.displayGuiScreen((GuiScreen)null);

            //run callback to allow for the parent gui to be opened
            this.parentScreen.confirmClicked(false, this.parentButtonClickedId);

            if (this.mc.currentScreen == null)
            {
                this.mc.setIngameFocus();
            }
        }
    }
```

Another step could be to add support for a parent screen to be opened automatically on close, reminescent of `SettingsUI`
