### ISSUE TITLE
SP screen breaks stack amount rendering

### ISSUE THREAD

**Issue by ryanzhoudev** [Wynntils/Wynntils-Legacy#384]
### Version

Build 1376 (development 7971b6010d4bdd696257525f79cbf9e4b80eb5bb)

### Brief Description

Opening the skill point menu (compass) removes the amount numbers for stacks of items in your inventory.

### Steps to Reproduce

- Keep a stack of items in your inventory, 2+ items so it shows the number
- Open compass menu
- Observe item stack

### Expected Behaviour

Stack amount still exists

### Actual Behaviour

Stack amount doesn't exist

### Installed Mods

Wynntils, Phosphor

**Comment by Incompleteusern** [comment]
image?

**Comment by magicus** [comment]
But the amount is restored when exiting the compass menu, right?
