### ISSUE TITLE
Dialogue problems

### ISSUE THREAD

**Issue by cmkohnen** [Wynntils/Wynntils-Legacy#391]
### Version

CE 1383

### Brief Description

New Dialogue will appear and clear all the text that was sent in chat before. However it will not vanish and simply stay in chat. This is an issue because it basically clears the cha
![2021-12-05_09 50 51](https://user-images.githubusercontent.com/59118042/144740151-d1a715ae-4572-4c47-bb04-4f09609ff47f.png)
![2021-12-05_09 51 41](https://user-images.githubusercontent.com/59118042/144740154-393bae03-6bf0-4329-9765-33a656bcb71b.png)
![2021-12-05_09 52 02](https://user-images.githubusercontent.com/59118042/144740156-166e1f95-f979-4165-99c5-0114a1db99f9.png)
t.

### Steps to Reproduce

Have any text in chat; start a dialogue with any npc

### Expected Behaviour

Dialogue text should disappear and old text be visible again.

### Actual Behaviour

Dialogue text does not disappear and old text is no longer readable.

### Installed Mods

![grafik](https://user-images.githubusercontent.com/59118042/144740313-5e063e9e-f941-4eef-8509-059d2e7d417d.png)
The problem consists when disabling all mods

**Comment by P0keDev** [comment]
Resolved as of #435

**Comment by cmkohnen** [comment]
Thanks!
