### ISSUE TITLE
Wynntils commands don't work in custom keybinds

### ISSUE THREAD

**Issue by ryanzhoudev** [Wynntils/Wynntils-Legacy#432]
### Version

CE 1428 cb59fab2092e4a2d9c5759e56d910d65fc6152f1

### Brief Description

Custom keybinds don't work for Wynntils commands. (Sent to server, returns invalid command)

### Steps to Reproduce

Assign a Wynntils command like `compass clear` to a custom bind
Press custom bind

### Expected Behaviour

Bind runs Wynntils command

### Actual Behaviour

Bind sends command to server and returns invalid command

### Installed Mods

Wynntils, Optifine, Phosphor

**Comment by kristofbolyai** [comment]
Thanks, making a PR with fix later today. We should just check if the command is a ClientCommand and execute the command the correct way based on the check.
