### ISSUE TITLE
Crash on wynncraft beta

### ISSUE THREAD

**Issue by Ayn4rch** [Wynntils/Wynntils-Legacy#44]
**Describe the bug**

My minecraft (1.12.1 with wynntils) crashed on the beta when I was trying to test the market place.
jpesent saw the crash report and told me it was wynntils so here I am.

**To Reproduce**

Seems like the crash happens when using the filter menu in the trading market too quickly ?

**Screenshots**

See crash reports attached.

**Versions:**
 - OS: Windows 8.1
 - Minecraft version: 1.12.1
 - Version: 0.1.7_496

**Additional context**
[crash-2019-01-17_06.59.09-client.txt](https://github.com/Wynntils/Wynntils/files/2767353/crash-2019-01-17_06.59.09-client.txt)
[crash-2019-01-17_07.02.23-client.txt](https://github.com/Wynntils/Wynntils/files/2767354/crash-2019-01-17_07.02.23-client.txt)
[crash-2019-01-17_07.06.04-client.txt](https://github.com/Wynntils/Wynntils/files/2767355/crash-2019-01-17_07.06.04-client.txt)

**Comment by CringeAura** [comment]
Hi, thanks for submitting a report.

Currently, we have a system in place on our Discord server for players to submit bug/crash reports and to request for support. Could you please resubmit this report on our Discord server for us to better assist you with your issue? If you need an invite link to the server, here it is (this invite will expire after one day): https://discord.gg/UvGFjT

**Comment by jpresent** [comment]
I've fixed this in #45

**Comment by Bedo9041** [comment]
Fixed by #45
