### ISSUE TITLE
No option to Disable Custom Class Selection

### ISSUE THREAD

**Issue by Pabsb** [Wynntils/Wynntils-Legacy#444]
### Version

1.10.5_655

### Brief Description

Can not disable custom class selection screen.

### Steps to Reproduce

No option in any settings whether searching or going through one by one of each category to disable the custom class selection screen.

### Expected Behaviour

Option to disable custom class selection screen.

### Actual Behaviour

No option at all to disable the custom class selection screen.

### Installed Mods

Just Wynntils.

**Comment by ryanzhoudev** [comment]
![image](https://user-images.githubusercontent.com/57310593/150484112-16d8949d-6e8c-4897-83a2-062762052115.png)

**Comment by magicus** [comment]
@Pabsb Would you suggest an alternative name or placement for this option, where it would have been easier for you to find?

**Comment by kristofbolyai** [comment]
> @Pabsb Would you suggest an alternative name or placement for this option, where it would have been easier for you to find?

Actually, adding search aliases would be helpful in some cases. I personally had trouble with this setting too. I always typed "class" "class menu" etc. So maybe we should consider that?
