### ISSUE TITLE
Open Chat not working

### ISSUE THREAD

**Issue by LordHarkon** [Wynntils/Wynntils-Legacy#464]
### Version

1.11.0

### Brief Description

The option to open the chat automatically when trying to input a text to search on the market does not work.

### Steps to Reproduce

1. Go to Configuration > Utilities > Market, and set the Open Chat options to enabled.
2. Open the market and go to `Search item`.
3. Select `Add Name Contains Filter`.
4. Bug occurs as the chat does not open automatically.

### Expected Behaviour

Chat should open after step 3 in `Steps to Reproduce`.

### Actual Behaviour

Chat does not open after step 3 in `Steps to Reproduce`.

### Installed Mods

- [Advanced Macros](https://www.curseforge.com/minecraft/mc-mods/advanced-macros)
- [ChestCoundMod](https://www.avicia.tk/chestcountmod)
- [Optifine](https://optifine.net)
- [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge)
- [Smooth Font](https://www.curseforge.com/minecraft/mc-mods/smooth-font)
- [StepUp](https://www.curseforge.com/minecraft/mc-mods/stepup)
- [Wynntils](https://ci.wynntils.com/job/Wynntils/lastSuccessfulBuild/artifact/build/libs/)

**Comment by kristofbolyai** [comment]
Do you receive a chat message when you click that button? Also, could you include logs?

**Comment by LordHarkon** [comment]
Yes, I receive the message `Type the item name or type 'cancel' to cancel:`
Here's a screenshot of the chat: https://imgur.com/52uHd1T
And here's the log until after I click the button and upon the chat manually: https://pastebin.com/7D7JPXaA

**Comment by kristofbolyai** [comment]
Can you try to see if this happens with only Wynntils installed?

**Comment by LordHarkon** [comment]
Ok, the problem was with the mod Advanced Macros. I had a pre-release version of the version that is now the latest (7.10.0) and it had a compatibility issue. I've updated the mod to the stable version and now the function works perfectly again.
