### ISSUE TITLE
Broken Formatting for Quest Rewards

### ISSUE THREAD

**Issue by ByThePowerOfScience** [Wynntils/Wynntils-Legacy#523]
### Version

1.11.0_656-MC1.12.2

### Brief Description

Ok, so! My dialogue patch in https://github.com/Wynntils/Wynntils/pull/512 did work, but it broke quest reward text!  Somehow! Apparently the thrown Exception made everything work properly?!?!?!
Well, I don't know how to fix that without VanillaFix going crazy every time someone speaks, but I figured I'd highlight the issue anyway.

### Steps to Reproduce

Complete a quest and receive rewards.

### Expected Behaviour

All quest rewards appear next to their bullet points, with no blank lines between quest rewards.

### Actual Behaviour

![2022-05-25_21 28 06](https://user-images.githubusercontent.com/16433721/170403889-123eb65b-658e-4ab7-8fc6-ff71a4ab2119.png)

### Installed Mods

I'm using the [Wynncraft Remastered](https://www.curseforge.com/minecraft/modpacks/wynncraft-remastered) modpack.

**Comment by ByThePowerOfScience** [comment]
Honestly maybe just revert the change and add a `catch` statement for the `ArrayIndexOutOfBoundsException` on the calling method. See if that fixes it.

**Comment by ryanzhoudev** [comment]
Was fixed in #518.
