### ISSUE TITLE
Slow and inconsistent spell casting

### ISSUE THREAD

**Issue by Ad4m69** [Wynntils/Wynntils-Legacy#541]
### Version

1.12.2

### Brief Description

the click to cast spell function cast spells at a slow unusable rate. and sometimes it misses some clicks

### Steps to Reproduce

casting spells using wynntils (z,x,c,v)

### Expected Behaviour

cast any spell at consistent, fast, reliable rate. (200-400ms per spell) without missing inputs

### Actual Behaviour

casting spells is slow unusable and sometimes misses some clicks

### Installed Mods

wynntils

**Comment by ryanzhoudev** [comment]
Was fixed in #574.
