### ISSUE TITLE
Totem glow making puppets glow

### ISSUE THREAD

**Issue by byBackfish** [Wynntils/Wynntils-Legacy#575]
### Version

1.12.1

### Brief Description

When using the ability where your totem summons puppets, the puppets will glow instead of the totem

### Steps to Reproduce

Activate the ability that summons puppets
Cast a totem

### Expected Behaviour

The totem to glow

### Actual Behaviour

The puppets glow

**Comment by HighCrit** [comment]
Is this not fixed in https://github.com/Wynntils/Wynntils/pull/569 :?

**Comment by ryanzhoudev** [comment]
Totem highlighting is disabled now. Can reopen if the issue still occurs after the next implementation of totem highlight/tracking.
