### ISSUE TITLE
Custom Bars don't reset

### ISSUE THREAD

**Issue by byBackfish** [Wynntils/Wynntils-Legacy#596]
### Version

1.12.1 (basically every other version as well)

### Brief Description

As the bossbar data (like focus, blood pool etc) are only updated when the bossbar is updated/sent, it does not reset to 0 when it should. Wynncraft fully removes your bossbar for Focus (and Awakened etc), but Wynntils doesn't recognize that it got removed, and the old data is kept

### Steps to Reproduce

Be on archer

Get the focus ability
Hit a shot with a bow

Miss a shot

### Expected Behaviour

Focus bar should be 0

### Actual Behaviour

Focus bar stays at 1

### Additional Comments

Im currently on a study trip. If anyone else wants to do this, feel free to. Otherwise, I would "fix" it once I'm back/have more time (at max in 3days)

**Comment by Robit** [comment]
To add to this, on the latest version of Wynnutils (curr. 1.13.0) I no longer see a focus bar at all
