### ISSUE TITLE
Crash with CreativeCore

### ISSUE THREAD

**Issue by ghost** [Wynntils/Wynntils-Legacy#635]
### Version

v0.0.1-alpha.19

### Brief Description

When using Wynntils Artemis and "recent" versions of 1.18.2 CreativeCore the game crashes during the initializing game phase

Although the crash is avoidable by using older versions of CreativeCore

### Steps to Reproduce

Have these mods in the mods folder:
[wynntils-0.0.1-alpha.19-fabric](https://www.curseforge.com/minecraft/mc-mods/wynntils/files/4074656)
[fabric-api-0.66.0+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4073282)
[CreativeCore_FABRIC_v2.6.12_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3827354)

Fabric Version 0.14.9

Launch the game and it will then crash during the games initialization

_Note:_
_This crash "seems to only happen" for all versions of CreativeCore between (inclusive):_
_[CreativeCore_FABRIC_v2.6.5_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3736276) to [CreativeCore_FABRIC_v2.6.12_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3827354)_

_Versions of [CreativeCore_FABRIC_v2.6.4_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3735159) and below do not seem to have this error_

### Crash Report

[crash-2022-11-08_22.03.24-client.txt](https://github.com/Wynntils/Wynntils/files/9967028/crash-2022-11-08_22.03.24-client.txt)

### Installed Mods

[wynntils-0.0.1-alpha.19-fabric](https://www.curseforge.com/minecraft/mc-mods/wynntils/files/4074656)
[fabric-api-0.66.0+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4073282)
[CreativeCore_FABRIC_v2.6.12_mc1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3827354)

**Comment by Incompleteusern** [comment]
Wrong repo, open issue at https://github.com/Wynntils/Artemis. Also this is likely going to be a wontfix

**Comment by ghost** [comment]
Moved to https://github.com/Wynntils/Artemis/issues/665
