### ISSUE TITLE
Cannot connect to Wynncraft with Debugify Mod

### ISSUE THREAD

**Issue by 2mal3** [Wynntils/Wynntils-Legacy#645]
### Version

v0.0.1-alpha.66

### Brief Description

When trying to connect to Wynncraft together with the [Debugify Mod](https://modrinth.com/mod/debugify), the following error message appears.
![image](https://user-images.githubusercontent.com/56305732/203111359-b0631cb8-0f3b-49c0-b0bc-c3d155e72d09.png)
No error message is displayed in the logs.

### Steps to Reproduce

1. install the mods mentioned below
2. launch Minecraft
2. don't change anything in the default settings of the mods
2. try to connect to Wynncraft

### Expected Behaviour

You can connect to Wynncraft without any problems.

### Actual Behaviour

You can't connect to Wynncraft.

### Installed Mods

Debugify 1.11.0
Fabric API 0.67.0
Wynntils 0.0.1-alpha.66

**Comment by kristofbolyai** [comment]
Firstly, wrong repo. Secondly, it is a known issue and is likely on debugify changing something weird internally. We are not fixing this until the 1.19.3 port.

**Comment by kristofbolyai** [comment]
https://github.com/Wynntils/Artemis
