### ISSUE TITLE
Game crashes on Startup

### ISSUE THREAD

**Issue by Overtank079** [Wynntils/Wynntils-Legacy#657]
### Version

wynntils-0.0.1-alpha.207-fabric

### Brief Description

When i open minecraft it crashes and says the reason of the crash is wynntils
![image](https://user-images.githubusercontent.com/34961961/213735735-72f12bb6-60ba-47af-a29c-bd3a0fbd5922.png)

### Steps to Reproduce

I'm not sure but all i do is open minecraft with a few mods

### Crash Report

[crash-2023-01-20_16.27.53-client.txt](https://github.com/Wynntils/Wynntils/files/10467627/crash-2023-01-20_16.27.53-client.txt)

**Comment by magicus** [comment]
@Overtank079 You need to download [v0.0.2-alpha.121](https://github.com/Wynntils/Artemis/releases/tag/untagged-721c868f2e949e903218).

Also, you reported this bug on the 1.12 version. In the future, please report Artemis bugs on Artemis.
