### ISSUE TITLE
Unable to exit dialogue with silverbull beacon npc

### ISSUE THREAD

**Issue by AndrewEllen** [Wynntils/Wynntils-Legacy#680]
### Version

v0.0.3-alpha.131

### Brief Description

The dialogue buttons don't work and the exit button is on number 13 which is inaccessible through the number 1-9 keys

### Steps to Reproduce

Talk to the beacon NPC in the silverbulls building near Cinfras. They are located in the back right section of the building.

### Expected Behaviour

Be able to click the dialogue options given.

### Actual Behaviour

The buttons are unclickable and the quick keybinds for selecting only go to the number 9 on the keyboard.

**Comment by magicus** [comment]
I understand if this is confusing, but you reported this on the project for the old 1.12 version. I copied the bug here: https://github.com/Wynntils/Artemis/issues/1745
