### ISSUE TITLE
Wynnic/ Gavellian Translation

### ISSUE THREAD

**Issue by izzy4234** [Wynntils/Wynntils-Legacy#683]
### Version

0.0.3 alpha.270 fabric

### Brief Description

Translation is not the same as it was in the version i was using for 1.12.2 where you could hover over a wynnic or gavellian text in the chat and it would display it as an overlay and would not overwrite it like it does now, also you could press shift in the inventory before and text on items as well would be temporarily translated, would be cool if these features came back since its kind of confusing whether people are typing wynnic in chat. no pushing it though.

### Steps to Reproduce

not really hard to reproduce just download the mod with its libraries and apis. along with fabric of course.

### Expected Behaviour

I'm not sure if it is supposed to be expected but it would be cool if it was added.

### Actual Behaviour

I know it already translates the text in chat, just wish it showed the original without being overwritten.

**Comment by kristofbolyai** [comment]
Wrong repo. Also, issues are not a place for feature requests.
