### ISSUE TITLE
Top right quest text missing spaces

### ISSUE THREAD

**Issue by LFGaming** [Wynntils/Wynntils-Legacy#684]
### Version

Version v0.0.3-alpha.291

### Brief Description

In the quest `An Iron Heart Part II` (maybe more but this one I found it) there are spaces missing in the top richt `Tracked Quest` part when there is a name of an NPC in the text.

Examples:
`Follow the west road and speak withDaxe in his home at ...`
`Escape the Golem Factory and findUrelix`

### Steps to Reproduce

Start tracking the `An Iron Heart Part II` and wait for a name to be in the text in the top right.

example pictures:

![image](https://github.com/Wynntils/Wynntils/assets/38732192/f47d8083-3291-4b1f-8520-5bbc427a57d4)

![javaw_2023-08-09_13-17-11](https://github.com/Wynntils/Wynntils/assets/38732192/ed28debe-ceff-4c8e-a321-be5855ec4f18)

example of another quest where the space is missing after the name (the Maiden tower quest with Shrek):
![javaw_2023-08-09_14-13-36](https://github.com/Wynntils/Wynntils/assets/38732192/4a8b93d2-8f34-4af6-89e6-368a6f4597a8)

### Expected Behaviour

I would expect a space between the words and the names

### Actual Behaviour

There is no space between the word before the name and the name itself

### Additional Comments

Ask me anything if you have questions about this bug here or on discord @lfgaming

### Installed Mods

wynntills,
fabric api,
lithium,
sodium,
WI-Zoom,
Iris

**Comment by ghost** [comment]
I've run into this issue as well, and I'm looking over the [relevant code](https://github.com/Wynntils/Wynntils/blob/71bf7fee9698345af1b61eb7f3b39c57b51fb497/src/main/java/com/wynntils/modules/questbook/overlays/hud/TrackedQuestOverlay.java#L15) right now.

### Installed Mods
Fabric API - `0.85.0+1.19.4`
Wynntils - `0.0.3-alpha.352`
Sodium - `0.4.10+build.24`
Lithium - `0.11.1`
Phosphor - `0.8.1`

**Comment by magicus** [comment]
This is a problem with Artemis, not Legacy.
