### ISSUE TITLE
QuestBook crash

### ISSUE THREAD

**Issue by Boyownik** [Wynntils/Wynntils-Legacy#69]
**Describe the bug**
When trying to open quest book, game crashes.

**To Reproduce**
1. Try to open quest book

**Versions:**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Version: 0.2_600

**Additional context**
Crash log: https://paste.dimdev.org/vebozuyute.mccrash

**Comment by HeyZeer0** [comment]
Fixed on the latest version, thanks for your report
