### ISSUE TITLE
Scoreboard field in lootruns (timer, challenges, etc...) does not update

### ISSUE THREAD

**Issue by Molioron** [Wynntils/Wynntils-Legacy#692]
### Version

0.0.4-beta.35 and 0.0.3-alpha.380

### Brief Description

The right side scoreboard UI does not update while there is a mission active (and possibly because the guild's weekly objective also appears)

Moreover, the latest beacon does not disappear upon completion.

### Steps to Reproduce

1. have a guild weekly objective
2. start a mission in a lootrun

### Expected Behaviour

the side scoreboard updates as usual (timer, number of challenges, etc...)

### Actual Behaviour

the side scoreboard will not update until the objective of the mission is complete.
the latest beacon does not disappear upon completion.

**Comment by kristofbolyai** [comment]
Wrong repo. Also it’s fixed now.
