### ISSUE TITLE
cape

### ISSUE THREAD

**Issue by tophackr** [Wynntils/Wynntils-Legacy#8]
how to disable mod cape?

**Comment by HeyZeer0** [comment]
Do /token inside the game, click on the provide token, register your password and now go to capes.wynntils.cf and login. After all of this you will see an option to disable your cape.

**Comment by tophackr** [comment]
<img width="314" alt="2018-11-07 19 19 06" src="https://user-images.githubusercontent.com/34376105/48144486-0f1ea700-e2c2-11e8-9ecd-c7e1fed715f0.png">
<img width="1085" alt="2018-11-07 19 19 13" src="https://user-images.githubusercontent.com/34376105/48144487-0f1ea700-e2c2-11e8-891a-8c473aad0ac1.png">
