### ISSUE TITLE
cape

### ISSUE THREAD

**Issue by tophackr** [Wynntils/Wynntils-Legacy#9]
how? #8 
<img width="314" alt="2018-11-07 19 19 06" src="https://user-images.githubusercontent.com/34376105/48157594-1dc88680-e2e1-11e8-918b-0bdc606b0451.png">
<img width="1085" alt="2018-11-07 19 19 13" src="https://user-images.githubusercontent.com/34376105/48157595-1e611d00-e2e1-11e8-9025-2f8116748049.png">

**Comment by DevScyu** [comment]
Working on it!

**Comment by DevScyu** [comment]
Fixed
